### PR TITLE
Added A03_barnetth

### PR DESCRIPTION
**Pull request by HaileyB0311**
Hello!

I would like to integrate my code.

Thank you,
Hailey Barnett

### CODE REVIEW

**Comment by emmet0r** [comment]
Can you please include a link to your Google doc in the header block?

**Comment by HaileyB0311** [comment]
Hello!


I believe that I have done as requested. My bad!


Hailey

________________________________

**Comment by emmet0r** [comment]
I still can't see it - can you make sure that you committed & pushed your changes? (You can click on the "Files Changed" tab to see what Scott & I can see.)

**Comment by HaileyB0311** [comment]
Hello!


I talked with Scott after class and the problem should be fixed now. Sorry about that!


Hailey

________________________________

**Pull request merged**
